{
 "title": "Throughput",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Identifications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Identifications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum({__name__=~\"maccoys_identifications_.*\", instance=~\".*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Search space generation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum({__name__=~\"maccoys_search_space_generation_.*\", instance=~\".*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scoring",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum({__name__=~\"maccoys_scorings_.*\", instance=~\".*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Publications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum({__name__=~\"maccoys_publication_.*\", instance=~\".*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum({__name__=~\"maccoys_errors_.*\", instance=~\".*\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}